/usr/local/bin/kubelet 
--v=0 --address=10.20.0.8 
--node-ip=10.20.0.8 
--hostname-override=node-5 
--pod-manifest-path=/etc/kubernetes/manifests 
--config=/etc/kubernetes/kubelet_config.yaml 
--pod-infra-container-image=hub.easystack.io/captain/pause-amd64:3.0 
--node-status-update-frequency=10s 
--client-ca-file=/etc/kubernetes/ssl/ca.pem 
--tls-cert-file=/etc/kubernetes/ssl/node-node-5.pem 
--tls-private-key-file=/etc/kubernetes/ssl/node-node-5-key.pem 
--anonymous-auth=false 
--authentication-token-webhook=true 
--authorization-mode=Webhook 
--max-pods=255 
--image-gc-whitelist=hub.easystack.io/captain/etcd:v3.5.7 
--cgroup-driver=cgroupfs --cgroups-per-qos=True 
--runtime-cgroups=/systemd/system.slice 
--kubelet-cgroups=/systemd/system.slice 
--event-qps=0 
--container-runtime=remote 
--runtime-request-timeout=15m 
--container-runtime-endpoint=unix:///run/containerd/containerd.sock 
--fail-swap-on=True 
--enforce-node-allocatable=pods 
--cluster-dns=10.222.0.3 
--cluster-domain=cluster.local 
--resolv-conf=/etc/resolv.conf 
--kubeconfig=/etc/kubernetes/node-kubeconfig.yaml 
--system-reserved cpu=1000m,memory=23140Mi 
--kubepods-cpuset.cpus=0-7 
--kubepods-cpuset.mems=0 
--feature-gates=ExpandPersistentVolumes=True,GracefulNodeShutdown=true 
--eviction-hard=memory.available<512Mi 
--eviction-soft-grace-period=memory.available=90s 
--eviction-max-pod-grace-period=120 
--runtime-request-timeout=10m 
--eviction-soft=memory.available<2048Mi --volume-plugin-dir=/var/lib/kubelet/volume-plugins